### ISSUE TITLE
Authentication not working. Login works with any credentials

### ISSUE THREAD

**Issue by sujith-mn** [devonfw/devon4ng-application-template#191]
Login with any credentials, no matter existing user or not, will takes the user to the home page.

Steps:

1. Start the application (ng serve).
2. Go to login page (http://localhost:4200/login)
3. Type username and password (it can be any character) and press Login.

Expected:
Stay back in the login page with error message "Wrong credentials"

**Comment by sujith-mn** [comment]
PR created https://github.com/devonfw/devon4ng-application-template/pull/192

**Comment by sjimenez77** [comment]
It seems that this issue was already solved, right @sujith-mn?

**Comment by sujith-mn** [comment]
@chdattat has fixed it, however i'll test it once again and close.

**Comment by sujith-mn** [comment]
Verified.. it is working as expected.
